# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170606_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activation',
            name='phone',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activation',
            name='used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterIndexTogether(
            name='activation',
            index_together=set([('phone', 'used')]),
        ),
    ]
