# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170606_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Baccarat',
        ),
    ]
