# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_baccarat'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='push_token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
