# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sound',
            field=models.BooleanField(default=True),
        ),
    ]
