# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_myuser_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='tariff',
            field=models.SmallIntegerField(choices=[(1, 'Демо'), (2, 'PRO')], db_index=True, default=1, verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='tariff_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата окончания'),
            preserve_default=False,
        ),
    ]
