# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170728_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='tariff_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
