# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170728_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sound_name',
            field=models.CharField(default='onesignal1', max_length=255),
        ),
    ]
