# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170731_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='push_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
    ]
