# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baccarat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=15, unique=True)),
                ('player', models.BooleanField(db_index=True, default=False)),
                ('banker', models.BooleanField(db_index=True, default=False)),
                ('tie', models.BooleanField(db_index=True, default=False)),
                ('either_pair', models.BooleanField(db_index=True, default=False)),
                ('big', models.BooleanField(db_index=True, default=False)),
                ('small', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('raw_result', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
