# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170620_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baccarat',
            name='banker_current',
        ),
        migrations.RemoveField(
            model_name='baccarat',
            name='big_current',
        ),
        migrations.RemoveField(
            model_name='baccarat',
            name='either_pair_current',
        ),
        migrations.RemoveField(
            model_name='baccarat',
            name='player_current',
        ),
        migrations.RemoveField(
            model_name='baccarat',
            name='small_current',
        ),
        migrations.RemoveField(
            model_name='baccarat',
            name='tie_current',
        ),
    ]
