# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_auto_20170620_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaccaratUserLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField(default=5)),
                ('banker', models.IntegerField(default=5)),
                ('tie', models.IntegerField(default=5)),
                ('either_pair', models.IntegerField(default=5)),
                ('big', models.IntegerField(default=5)),
                ('small', models.IntegerField(default=5)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
