# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_baccaratuserlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='baccaratlimit',
            name='banker_count_till',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='banker_default',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='big_count_till',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='big_default',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='either_pair_count_till',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='either_pair_default',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='player_count_till',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='player_default',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='small_count_till',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='small_default',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='tie_count_till',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='baccaratlimit',
            name='tie_default',
            field=models.IntegerField(default=48),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='banker_max',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='banker_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='big_max',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='big_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='either_pair_max',
            field=models.IntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='either_pair_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='player_max',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='player_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='small_max',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='small_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='tie_max',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='baccaratlimit',
            name='tie_min',
            field=models.IntegerField(default=1),
        ),
    ]
