# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170621_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=15, unique=True)),
                ('one_pair', models.BooleanField(db_index=True, default=False)),
                ('two_pair', models.BooleanField(db_index=True, default=False)),
                ('three_of_a_kind', models.BooleanField(db_index=True, default=False)),
                ('straight', models.BooleanField(db_index=True, default=False)),
                ('flash', models.BooleanField(db_index=True, default=False)),
                ('full_house', models.BooleanField(db_index=True, default=False)),
                ('hand', models.IntegerField(db_index=True, default=1)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
