# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_poker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poker',
            old_name='two_pair',
            new_name='two_pairs',
        ),
    ]
