# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20170623_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poker',
            old_name='flash',
            new_name='flush',
        ),
    ]
