# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20170623_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poker',
            name='hand',
            field=models.CharField(db_index=True, default='1', max_length=25),
        ),
    ]
