# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20170623_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='poker',
            name='four_of_a_kind',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
