# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_pokerlimit_pokeruserlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='baccaratuserlimit',
            name='banker_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baccaratuserlimit',
            name='big_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baccaratuserlimit',
            name='either_pair_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baccaratuserlimit',
            name='player_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baccaratuserlimit',
            name='small_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baccaratuserlimit',
            name='tie_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pokeruserlimit',
            name='flush_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pokeruserlimit',
            name='four_of_a_kind_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pokeruserlimit',
            name='full_house_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pokeruserlimit',
            name='one_pair_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pokeruserlimit',
            name='straight_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pokeruserlimit',
            name='three_of_a_kind_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pokeruserlimit',
            name='two_pairs_push',
            field=models.BooleanField(default=True),
        ),
    ]
