# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170725_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warbets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=15, unique=True)),
                ('player', models.BooleanField(db_index=True, default=False)),
                ('diller', models.BooleanField(db_index=True, default=False)),
                ('draw', models.BooleanField(db_index=True, default=False)),
                ('player_red', models.BooleanField(db_index=True, default=False)),
                ('diller_red', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
