# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20170725_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=15, unique=True)),
                ('d1_to_d6', models.BooleanField(db_index=True, default=False)),
                ('d7_to_d12', models.BooleanField(db_index=True, default=False)),
                ('d13_to_d18', models.BooleanField(db_index=True, default=False)),
                ('less', models.BooleanField(db_index=True, default=False)),
                ('more', models.BooleanField(db_index=True, default=False)),
                ('grey', models.BooleanField(db_index=True, default=False)),
                ('red', models.BooleanField(db_index=True, default=False)),
                ('black', models.BooleanField(db_index=True, default=False)),
                ('even', models.BooleanField(db_index=True, default=False)),
                ('odd', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
