# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0017_wheel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1_to_d6_min', models.IntegerField(default=1)),
                ('d1_to_d6_max', models.IntegerField(default=20)),
                ('d1_to_d6_default', models.IntegerField(default=15)),
                ('d1_to_d6_count_till', models.IntegerField(default=30)),
                ('d7_to_d12_min', models.IntegerField(default=1)),
                ('d7_to_d12_max', models.IntegerField(default=20)),
                ('d7_to_d12_default', models.IntegerField(default=15)),
                ('d7_to_d12_count_till', models.IntegerField(default=30)),
                ('d13_to_d18_min', models.IntegerField(default=1)),
                ('d13_to_d18_max', models.IntegerField(default=20)),
                ('d13_to_d18_default', models.IntegerField(default=15)),
                ('d13_to_d18_count_till', models.IntegerField(default=30)),
                ('less_min', models.IntegerField(default=1)),
                ('less_max', models.IntegerField(default=20)),
                ('less_default', models.IntegerField(default=15)),
                ('less_count_till', models.IntegerField(default=30)),
                ('more_min', models.IntegerField(default=1)),
                ('more_max', models.IntegerField(default=20)),
                ('more_default', models.IntegerField(default=15)),
                ('more_count_till', models.IntegerField(default=30)),
                ('grey_min', models.IntegerField(default=1)),
                ('grey_max', models.IntegerField(default=20)),
                ('grey_default', models.IntegerField(default=15)),
                ('grey_count_till', models.IntegerField(default=30)),
                ('black_min', models.IntegerField(default=1)),
                ('black_max', models.IntegerField(default=20)),
                ('black_default', models.IntegerField(default=15)),
                ('black_count_till', models.IntegerField(default=30)),
                ('red_min', models.IntegerField(default=1)),
                ('red_max', models.IntegerField(default=20)),
                ('red_default', models.IntegerField(default=15)),
                ('red_count_till', models.IntegerField(default=30)),
                ('even_min', models.IntegerField(default=1)),
                ('even_max', models.IntegerField(default=20)),
                ('even_default', models.IntegerField(default=15)),
                ('even_count_till', models.IntegerField(default=30)),
                ('odd_min', models.IntegerField(default=1)),
                ('odd_max', models.IntegerField(default=20)),
                ('odd_default', models.IntegerField(default=15)),
                ('odd_count_till', models.IntegerField(default=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['active'],
            },
        ),
        migrations.CreateModel(
            name='WheelUserLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1_to_d6', models.IntegerField(default=10)),
                ('d1_to_d6_push', models.BooleanField(db_index=True, default=False)),
                ('d7_to_d12', models.IntegerField(default=10)),
                ('d7_to_d12_push', models.BooleanField(db_index=True, default=False)),
                ('d13_to_d18', models.IntegerField(default=10)),
                ('d13_to_d18_push', models.BooleanField(db_index=True, default=False)),
                ('less', models.IntegerField(default=10)),
                ('less_push', models.BooleanField(db_index=True, default=False)),
                ('more', models.IntegerField(default=10)),
                ('more_push', models.BooleanField(db_index=True, default=False)),
                ('grey', models.IntegerField(default=10)),
                ('grey_push', models.BooleanField(db_index=True, default=False)),
                ('red', models.IntegerField(default=10)),
                ('red_push', models.BooleanField(db_index=True, default=False)),
                ('black', models.IntegerField(default=10)),
                ('black_push', models.BooleanField(db_index=True, default=False)),
                ('even', models.IntegerField(default=10)),
                ('even_push', models.BooleanField(db_index=True, default=False)),
                ('odd', models.IntegerField(default=10)),
                ('odd_push', models.BooleanField(db_index=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
