# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_wheellimit_wheeluserlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceDuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=15, unique=True)),
                ('red', models.IntegerField(default=0)),
                ('blue', models.IntegerField(default=0)),
                ('red_win', models.BooleanField(db_index=True, default=False)),
                ('blue_win', models.BooleanField(db_index=True, default=False)),
                ('draw', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
