# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0019_diceduel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceDuelLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_win_min', models.IntegerField(default=1)),
                ('red_win_max', models.IntegerField(default=20)),
                ('red_win_default', models.IntegerField(default=15)),
                ('red_win_count_till', models.IntegerField(default=30)),
                ('blue_win_min', models.IntegerField(default=1)),
                ('blue_win_max', models.IntegerField(default=20)),
                ('blue_win_default', models.IntegerField(default=15)),
                ('blue_win_count_till', models.IntegerField(default=30)),
                ('draw_min', models.IntegerField(default=1)),
                ('draw_max', models.IntegerField(default=20)),
                ('draw_default', models.IntegerField(default=15)),
                ('draw_count_till', models.IntegerField(default=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['active'],
            },
        ),
        migrations.CreateModel(
            name='DiceDuelUserLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_win', models.IntegerField(default=10)),
                ('blue_win_push', models.BooleanField(db_index=True, default=False)),
                ('red_win', models.IntegerField(default=10)),
                ('red_win_push', models.BooleanField(db_index=True, default=False)),
                ('draw', models.IntegerField(default=10)),
                ('draw_push', models.BooleanField(db_index=True, default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
