# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_diceduellimit_dicedueluserlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicedueluserlimit',
            name='blue_win_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='dicedueluserlimit',
            name='draw_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='dicedueluserlimit',
            name='red_win_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
