# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20170731_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='warbetslimit',
            name='just_black_count_till',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='warbetslimit',
            name='just_black_default',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='warbetslimit',
            name='just_black_max',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='warbetslimit',
            name='just_black_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='warbetslimit',
            name='just_red_count_till',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='warbetslimit',
            name='just_red_default',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='warbetslimit',
            name='just_red_max',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='warbetslimit',
            name='just_red_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='warbetsuserlimit',
            name='just_black',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='warbetsuserlimit',
            name='just_black_push',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='warbetsuserlimit',
            name='just_red',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='warbetsuserlimit',
            name='just_red_push',
            field=models.BooleanField(default=True),
        ),
    ]
