# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20170731_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheeluserlimit',
            name='black_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='wheeluserlimit',
            name='d13_to_d18_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='wheeluserlimit',
            name='d1_to_d6_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='wheeluserlimit',
            name='d7_to_d12_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='wheeluserlimit',
            name='even_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='wheeluserlimit',
            name='grey_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='wheeluserlimit',
            name='less_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='wheeluserlimit',
            name='more_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='wheeluserlimit',
            name='odd_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='wheeluserlimit',
            name='red_push',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
