# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20170731_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baccaratuserlimit',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='dicedueluserlimit',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='pokeruserlimit',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='warbetsuserlimit',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='wheeluserlimit',
            options={'ordering': ['-created_time']},
        ),
    ]
